name: SonarQube Scan

on:
  push:
    branches:
      - main
      - master

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -sSfL https://get.sonar-scanner.io | bash
          ./sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey="test.streamlit.example" \
            -Dsonar.host.url=http://ec2-44-220-54-251.compute-1.amazonaws.com:9000 \
            -Dsonar.login=$SONAR_TOKEN